### ISSUE TITLE
remove libvirt legacy code or do not call it by default 

### ISSUE THREAD

**Issue by vmindru** [leapp-to/leapp#236]
Executing: /usr/bin/leapp-tool check-target 127.0.0.1
2017-06-27T16:31:04.571Z - Loading used applications names from the target...

2017-06-27T16:31:04.897Z - > libvirt: XML-RPC error : Failed to connect socket to '/var/run/libvirt/libvirt-sock': No such file or directory

2017-06-27T16:31:04.897Z - > Traceback (most recent call last):

2017-06-27T16:31:04.897Z - >   File "/usr/bin/leapp-tool", line 9, in 

2017-06-27T16:31:04.897Z - >     load_entry_point('leappto==0.0.1-32.git.79.ce3ca6cNone', 'console_scripts', 'leapp-tool')()

2017-06-27T16:31:04.898Z - >   File "/usr/lib/python2.7/site-packages/leappto/cli.py", line 705, in main

2017-06-27T16:31:04.898Z - >     lmp = LibvirtMachineProvider()

2017-06-27T16:31:04.898Z - >   File "/usr/lib/python2.7/site-packages/leappto/providers/libvirt.py", line 31, in __init__

2017-06-27T16:31:04.898Z - >     self._connection = libvirt.open('qemu:///system')

2017-06-27T16:31:04.898Z - >   File "/usr/lib64/python2.7/site-packages/libvirt.py", line 255, in open

2017-06-27T16:31:04.898Z - >     if ret is None:raise libvirtError('virConnectOpen() failed')

2017-06-27T16:31:04.898Z - > libvirt.libvirtError: Failed to connect socket to '/var/run/libvirt/libvirt-sock': No such file or directory

2017-06-27T16:31:04.898Z - > Exception AttributeError: "'LibvirtMachineProvider' object has no attribute '_connection'" in > ignored

**Comment by vinzenz** [comment]
#267  is taking care of this
