### ISSUE TITLE
Missing dependencies for leappctl

### ISSUE THREAD

**Issue by vojtechsokol** [leapp-to/leapp#296]
Steps to reproduce the bug:

1. Install leapp from copr repository and try to run the leappctl tool
```shell
root@fedora-26:~# dnf copr enable -y @leapp/leapp-devel && dnf install leapp
...

root@fedora-26:~# leappctl
Traceback (most recent call last):
  File "/usr/bin/leappctl", line 11, in <module>
    load_entry_point('leappctl==0.0.1', 'console_scripts', 'leappctl')()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 572, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2749, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2402, in load
    return self.resolve()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2408, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/site-packages/leappctl/cli.py", line 4, in <module>
    import click
ImportError: No module named click
```

2. Intall missing dependency and try again
```shell
root@fedora-26:~# dnf install python2-click
...

root@fedora-26:~# leappctl
Traceback (most recent call last):
  File "/usr/bin/leappctl", line 11, in <module>
    load_entry_point('leappctl==0.0.1', 'console_scripts', 'leappctl')()
  File "/usr/lib/python2.7/site-packages/leappctl/cli.py", line 31, in main
    load_commands()
  File "/usr/lib/python2.7/site-packages/leappctl/cli.py", line 26, in load_commands
    mod = importer.find_module(name).load_module(name)
  File "/usr/lib64/python2.7/pkgutil.py", line 246, in load_module
    mod = imp.load_module(fullname, self.file, self.filename, self.etc)
  File "/usr/lib/python2.7/site-packages/leappctl/cmd/check_system.py", line 5, in <module>
    from leappctl.session import post
  File "/usr/lib/python2.7/site-packages/leappctl/session.py", line 4, in <module>
    import requests
ImportError: No module named requests
```

3. One more round
```shell
root@fedora-26:~# dnf install python2-requests
...

root@fedora-26:~# leappctl
Usage: leappctl [OPTIONS] COMMAND [ARGS]...

  This tool is designed to help the administrator control the functioning of
  leapp-daemon.

Options:
  --version  Show the version and exit.
  --help     Show this message and exit.

Commands:
  check-system       Run a group of checks on the system
  check-target       This command checks services (like Docker,...
  destroy-container  This command destroy a container by name on a...
  migrate-machine    Executes the migration of an OS into a macrocontainer
  port-inspect       This command scans ports on a target system
  port-map           Commmand that scans ports on source and...
```

**Comment by vinzenz** [comment]
Closing this issue - As this is no longer applicable
