### ISSUE TITLE
Two copies of osversion actor

### ISSUE THREAD

**Issue by vojtechsokol** [leapp-to/leapp#297]
Steps to reproduce the bug:

1. Install leapp from copr repository and try to run the `osversion` actor
```shell
root@fedora-26:~# dnf copr enable -y @leapp/leapp-devel && dnf install leapp
...

root@fedora-26:~# /usr/libexec/leapp/snactor_runner --actors_dir /usr/share/leapp/actors/ --schemas_dir /usr/share/leapp/schemas/ osversion
Traceback (most recent call last):
  File "/usr/libexec/leapp/snactor_runner", line 131, in <module>
    main()
  File "/usr/libexec/leapp/snactor_runner", line 102, in main
    load_actors(actors_dir, schemas_dir)
  File "/usr/libexec/leapp/snactor_runner", line 78, in load_actors
    load(actors_dir)
  File "/usr/lib/python2.7/site-packages/snactor/loader/__init__.py", line 85, in load
    _load(os.path.basename(root), os.path.join(root, '_actor.yaml'), tags, post_resolve)
  File "/usr/lib/python2.7/site-packages/snactor/loader/__init__.py", line 38, in _load
    create_actor(name, d)
  File "/usr/lib/python2.7/site-packages/snactor/loader/__init__.py", line 48, in create_actor
    register_actor(name, Definition(name, definition), executor)
  File "/usr/lib/python2.7/site-packages/snactor/registry/actors.py", line 24, in register_actor
    raise LookupError("Actor '{}' has been already registered previously".format(name))
LookupError: Actor 'osversion' has been already registered previously
```
The problem is that there are two copies of osversion actor, one from [leapp-actors](https://github.com/leapp-to/leapp-actors/tree/master/src/actors/containerization/common/osversion), second from [snactor examples](https://github.com/leapp-to/snactor/tree/master/examples/actors/osversion)

```shell
root@fedora-26:~# find /usr/share/leapp/actors/ -name osversion.py -type f
/usr/share/leapp/actors/containerization/common/osversion/osversion.py
/usr/share/leapp/actors/osversion/osversion.py
```

When one of the actor is deleted, everything works as expected
```shell
root@fedora-26:~# rm -rf /usr/share/leapp/actors/osversion
root@fedora-26:~# /usr/libexec/leapp/snactor_runner --actors_dir /usr/share/leapp/actors/ --schemas_dir /usr/share/leapp/schemas/ osversion
{"osversion": [{"version": "26", "name": "Fedora"}]}
```

**Comment by vinzenz** [comment]
Closing this issue - As this is no longer applicable
