### ISSUE TITLE
ModelViolationError when consuming model with fields.Nested 

### ISSUE THREAD

**Issue by artmello** [leapp-to/leapp#334]
As the process of writing new actors for a task, I am trying to replicate the data provided by a web service via an API into a Leapp model. The model would consists of a list of entries, with each entry consisting on multiples fields. One of this fields would have sub fields, which I am modelling using as a fields.Nested of another model. As an example, the model looks similar to this:
```
from leapp.models import Model, fields
from leapp.topics import SampleTopic


class Sample(Model):
    topic = SampleTopic

    field1 = fields.Integer()
    field2 = fields.String(allow_null=True)


class SampleNested(Model):
    topic = SampleTopic

    data = fields.Nested(Sample, default=None, allow_null=True)


class SampleNestedList(Model):
    topic = SampleTopic

    items = fields.List(fields.Nested(SampleNested), default=[])
```
I created an actor that will produce data using the previous model:
```
from leapp.actors import Actor
from leapp.models import SampleNestedList, SampleNested, Sample
from leapp.tags import SampleTag


class SampleProduce(Actor):
    name = 'sample_produce'
    description = 'No description has been provided for the sample_produce actor.'
    consumes = ()
    produces = (SampleNestedList,)
    tags = (SampleTag,)

    def process(self):
        sample_nested_list = SampleNestedList()
        for i in range(5):
            item = SampleNested()

            item.data = Sample()
            item.data.field1 = i
            item.data.field2 = str(i)
            
            sample_nested_list.items.append(item)

        self.produce(sample_nested_list)
```
This seems to work as expected:
```
$ snactor run --print-output SampleProduce
2018-06-26 18:12:14.790 INFO     PID: 15096 leapp: Logging has been initialized
2018-06-26 18:12:14.807 INFO     PID: 15096 leapp.repository.nested-check: A new repository 'nested-check' is initialized at /home/amello/dump/leapp/nested-check
[
  {
    "type": "SampleNestedList",
    "actor": "sample_produce",
    "topic": "sample",
    "stamp": "2018-06-26T18:12:14.850022Z",
    "phase": "NON-WORKFLOW-EXECUTION",
    "context": "d3476cad-5a02-48a7-8c00-be04c36c33b5",
    "hostname": "brewery",
    "message": {
      "data": "{\"items\": [{\"data\": {\"field1\": 0, \"field2\": \"0\"}}, {\"data\": {\"field1\": 1, \"field2\": \"1\"}}, {\"data\": {\"field1\": 2, \"field2\": \"2\"}}, {\"data\": {\"field1\": 3, \"field2\": \"3\"}}, {\"data\": {\"field1\": 4, \"field2\": \"4\"}}]}",
      "hash": "d3618e170a94a388ae7bf592a9fc00cef058a6a9ce67b92ec3f938aa3269dc42"
    }
  }
```
But the problem happens when I try to consume such data. I wrote the following actor to consumes the same model:
```from leapp.actors import Actor
from leapp.models import SampleNestedList
from leapp.tags import SampleTag


class SampleConsume(Actor):
    name = 'sample_consume'
    description = 'No description has been provided for the sample_consume actor.'
    consumes = (SampleNestedList,)
    produces = ()
    tags = (SampleTag,)

    def process(self):
        for items in self.consume(SampleNestedList):
            print(items)
```
But when we try to run the actor:
```
$ snactor run --print-output SampleConsume
2018-06-26 18:16:38.375 INFO     PID: 15160 leapp: Logging has been initialized
2018-06-26 18:16:38.388 INFO     PID: 15160 leapp.repository.nested-check: A new repository 'nested-check' is initialized at /home/amello/dump/leapp/nested-check
Process Process-4:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.6/site-packages/leapp/repository/actor_definition.py", line 53, in _do_run
    target_actor(logger=logger, messaging=messaging).run(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/leapp/actors/__init__.py", line 104, in run
    self.process(*args)
  File "/home/amello/dump/leapp/nested-check/actors/sampleconsume/actor.py", line 14, in process
    for items in self.consume(SampleNestedList):
  File "/usr/lib/python3.6/site-packages/leapp/messaging/__init__.py", line 147, in <genexpr>
    return (lookup[message['type']].create(json.loads(message['message']['data'])) for message in messages)
  File "/usr/lib/python3.6/site-packages/leapp/models/__init__.py", line 103, in create
    return cls(init_method='to_model', **data)
  File "/usr/lib/python3.6/site-packages/leapp/models/__init__.py", line 79, in __init__
    getattr(type(self).fields[field], init_method)(kwargs, field, self)
  File "/usr/lib/python3.6/site-packages/leapp/models/fields/__init__.py", line 130, in to_model
    target_value = self._convert_to_model(value=source_value, name=name)
  File "/usr/lib/python3.6/site-packages/leapp/models/fields/__init__.py", line 396, in _convert_to_model
    return list(converter(entry, name='{}[{}]'.format(name, idx)) for idx, entry in enumerate(value))
  File "/usr/lib/python3.6/site-packages/leapp/models/fields/__init__.py", line 396, in <genexpr>
    return list(converter(entry, name='{}[{}]'.format(name, idx)) for idx, entry in enumerate(value))
  File "/usr/lib/python3.6/site-packages/leapp/models/fields/__init__.py", line 444, in _convert_to_model
    return self._model_type(**value)
  File "/usr/lib/python3.6/site-packages/leapp/models/__init__.py", line 79, in __init__
    getattr(type(self).fields[field], init_method)(kwargs, field, self)
  File "/usr/lib/python3.6/site-packages/leapp/models/fields/__init__.py", line 114, in from_initialization
    self._validate_model_value(value=source_value, name=name)
  File "/usr/lib/python3.6/site-packages/leapp/models/fields/__init__.py", line 433, in _validate_model_value
    self._model_type.__name__, name, value, type(value)))
leapp.models.fields.ModelViolationError: Expected an instance of Sample for the data attribute but got {'field1': 0, 'field2': '0'} of type <class 'dict'>
Traceback (most recent call last):
  File "/usr/bin/snactor", line 11, in <module>
    load_entry_point('leapp==0.3', 'console_scripts', 'snactor')()
  File "/usr/lib/python3.6/site-packages/leapp/snactor/__init__.py", line 65, in main
    cli.command.execute(version='snactor version {}'.format(VERSION))
  File "/usr/lib/python3.6/site-packages/leapp/utils/clicmd.py", line 81, in execute
    args.func(args)
  File "/usr/lib/python3.6/site-packages/leapp/utils/clicmd.py", line 103, in called
    self.target(args)
  File "/usr/lib/python3.6/site-packages/leapp/utils/project.py", line 17, in checker
    return f(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/leapp/snactor/context.py", line 22, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/leapp/snactor/commands/run.py", line 42, in cli
    actor(messaging=messaging, logger=actor_logger).run()
  File "/usr/lib/python3.6/site-packages/leapp/repository/actor_definition.py", line 65, in run
    .format(actorname=self.definition.name, exitcode=p.exitcode))
leapp.exceptions.LeappRuntimeError: Actor sample_consume unexpectedly terminated with exit code: 1
```
I can see it fails during validation of the model. Expected an instance of Sample but receiving a "dict". For sure I can use a less complicated model removing fields.Nested, but would like to check if this is an usage error from my side or a real bug.

**Comment by vinzenz** [comment]
Thanks for this awesome bug report - I found the cause and I am about to push the fix.
