### ISSUE TITLE
snactor run <typo>    - raises an AttributeError

### ISSUE THREAD

**Issue by radomil** [leapp-to/leapp#354]
When I mistyped an actor name I faced this traceback.

`Traceback (most recent call last):
  File "/usr/bin/snactor", line 9, in <module>
    load_entry_point('leapp==0.3', 'console_scripts', 'snactor')()
  File "/usr/lib/python2.7/site-packages/leapp/snactor/__init__.py", line 68, in main
    cli.command.execute(version='snactor version {}'.format(VERSION))
  File "/usr/lib/python2.7/site-packages/leapp/utils/clicmd.py", line 81, in execute
    args.func(args)
  File "/usr/lib/python2.7/site-packages/leapp/utils/clicmd.py", line 103, in called
    self.target(args)
  File "/usr/lib/python2.7/site-packages/leapp/utils/repository.py", line 20, in checker
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/leapp/snactor/context.py", line 22, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/leapp/snactor/commands/run.py", line 40, in cli
    messaging.load(actor.consumes)
AttributeError: 'NoneType' object has no attribute 'consumes'
`

**Comment by vojtechsokol** [comment]
This should be already fixed in this PR: #351
